# Generated by Django 5.1.4 on 2024-12-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blogposts_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
